module.exports = {
apps: [
{
name: 'indiacrm-api',
script: 'dist/server/index.js',
instances: 'max',
exec_mode: 'cluster',
env: {
NODE_ENV: 'development',
PORT: 4000,
},
env_production: {
NODE_ENV: 'production',
PORT: 4000,
},
max_memory_restart: '1G',
error_file: 'logs/pm2-error.log',
out_file: 'logs/pm2-out.log',
log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
merge_logs: true,
autorestart: true,
watch: false,
restart_delay: 4000,
max_restarts: 10,
min_uptime: '10s',
},
},
{
name: 'indiacrm-worker',
script: 'dist/server/worker.js',
instances: 1,
exec_mode: 'fork',
env: {
NODE_ENV: 'development',
},
env_production: {
NODE_ENV: 'production',
},
error_file: 'logs/worker-error.log',
out_file: 'logs/worker-out.log',
log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
autorestart: true,
watch: false,
restart_delay: 4000,
max_restarts: 10,
min_uptime: '10s',
},
},
],
};